##  Introduction to Numpy

In [21]:
import numpy as np

In [22]:
arr = np.array([3,4,5,67,78])

In [31]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Conversion from other python struct

In [24]:
zeroes = np.zeros((2,5))
print(zeroes)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
ranges =  np.arange(15)
print(ranges)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [28]:
linesp = np.linspace(1,5,12)
linesp

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.02359984e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        1.29060531e-306, 1.33511562e-306, 2.22522596e-306]])

In [32]:
ranges.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [37]:
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Return the sum of leftmst element of array**

In [38]:
arr.sum(axis=0)

array([12, 15, 18])

**Transpose of matrix with T**

In [40]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])