In [3]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Math': [85, 90, 78, 92, 88],
    'Science': [88, 85, 82, 90, 87],
    'English': [90, 88, 85, 80, 92]
}

df = pd.DataFrame(data)


In [5]:
grades = df[['Math','Science','English']].to_numpy()

In [6]:
print(grades)

[[85 88 90]
 [90 85 88]
 [78 82 85]
 [92 90 80]
 [88 87 92]]


In [9]:
studentavg = np.average(grades,axis=1)
df['Average'] = studentavg
print(df)

   Student  Math  Science  English    Average
0    Alice    85       88       90  87.666667
1      Bob    90       85       88  87.666667
2  Charlie    78       82       85  81.666667
3    David    92       90       80  87.333333
4      Eve    88       87       92  89.000000


In [14]:
sd = np.std(grades,axis=0,ddof=1)
print(sd)

[5.45893763 3.04959014 4.69041576]


## filter logic with different queries


In [15]:
filterstud = np.average(grades,axis=1) > 85
print(filterstud)

[ True  True False  True  True]


In [16]:
fstd = df.query('Average > 85')
print(fstd)

  Student  Math  Science  English    Average  Standard deviation
0   Alice    85       88       90  87.666667            2.054805
1     Bob    90       85       88  87.666667            2.054805
3   David    92       90       80  87.333333            5.249339
4     Eve    88       87       92  89.000000            2.160247


In [18]:
arr = np.array([1,2,3,4,5])
print(arr * 3)


[ 3  6  9 12 15]


In [22]:
temps = np.array([72, 68, 75, 70, 73])
avgtemp = temps.mean(axis=0)
print("Average temperature : ",avgtemp)


Average temperature :  71.6


In [23]:
maxtemp = temps.max()
print(maxtemp)

75


In [27]:
matrixarr = np.arange(1,10).reshape(3,3)
print(matrixarr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
scores = np.array([85, 92, 78, 95, 88, 90])
total = np.sum(scores)
print(total)

Total score 528


In [32]:
#Average
avg = np.average(scores)
print(avg)

88.0


In [33]:
#sorted 
sort = np.sort(scores)

In [34]:
print(sort)

[78 85 88 90 92 95]


In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a-b)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]


In [47]:
data = {
    "Name":['Pablo','Denver','Arthur Morgan'],
    "Age":[54,20,44],
    "city":['New york','London','Paris']
}

df = pd.DataFrame(data)
print(df)

            Name  Age      city
0          Pablo   54  New york
1         Denver   20    London
2  Arthur Morgan   44     Paris


In [48]:
print(df.head(2))

     Name  Age      city
0   Pablo   54  New york
1  Denver   20    London


In [49]:
print(df['Name'])

0            Pablo
1           Denver
2    Arthur Morgan
Name: Name, dtype: object


In [50]:
print(df.iloc[1])

Name    Denver
Age         20
city    London
Name: 1, dtype: object


In [55]:
younger = df.query('Age < 25')
print(younger)

     Name  Age    city
1  Denver   20  London


In [ ]:

df['Adult'] = df['Age']>25 # boolean
print(df)

            Name  Age      city  Adult
0          Pablo   54  New york   True
1         Denver   20    London  False
2  Arthur Morgan   44     Paris   True


In [58]:
items = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],
    'Sales': [1200, 800, 450, 950, 700],
    'Region': ['East', 'West', 'East', 'West', 'East']
}

df2 = pd.DataFrame(items)


In [63]:
tot = df2['Sales'].sum()
print("total sales",tot)

total sales 4100


In [66]:
avgg = df2.groupby('Region')['Sales'].mean()
print(avgg)

Region
East    783.333333
West    875.000000
Name: Sales, dtype: float64


In [65]:
mxx = df2['Sales'].max()
print(mxx)

1200
